name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Log Level
        run: |
          echo "Log level: ${{ inputs.logLevel }}"
      - name: Print env GITHUB_WORKSPACE
        run: |
          echo "GITHUB_WORKSPAKCE location: ${{ env.GITHUB_WORKSPACE }}"
          echo $GITHUB_WORKSPACE
          echo $GITHUB_ENV
          echo $PATH
