name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
env:
  DB_NAME: my_db_name
  WHERE_TO_GRAB_SECRETS: TEST
jobs:
  first-job:
    environment: ${{ env.WHERE_TO_GRAB_SECRETS }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Log Level
        run: |
          echo "Log level: ${{ inputs.logLevel }}"
      - name: Print DB_NAME env
        run: |
          echo $DB_NAME
          echo "${{ env.DB_NAME }}"
      - name: Print env GITHUB_WORKSPACE
        run: |
          echo $GITHUB_WORKSPACE
          echo "${{ env.GITHUB_WORKSPACE }}"
      - name: Print env PATH
        run: |
          echo $PATH
          echo "${{ env.PATH }}"
      - name: Test print secret DB_PASSWORD
        run: |
          echo "${{ secrets.DB_PASSWORD }}"
          
